remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: My Intro to Digital Humanities Portofolio for Fall 2024
description: A portfolio of my projects in the Intro to Digital Humanities class, Fall 2024
